### ISSUE TITLE
Can I replace vicuna with another model based on llama?

### ISSUE THREAD

**Issue by yuanlisky** [Vision-CAIR/MiniGPT-4#249]
Can I replace vicuna with another model based on llama?
then train the model with two stages？

**Comment by TsuTikgiau** [comment]
I think yes

**Comment by yuanlisky** [comment]
> I think yes

Do I need to retrain the first stage
or I can start with stage 2?

**Comment by Sypherd** [comment]
Stage one is focused on aligning the language and vision models, so the alignments are specific to the model (that's why there are different checkpoints for first stage Vicuna 7B and 13B). If you are changing out the LLM, you would have to align the vision model and new LLM (stage one) and finetune the new LLM (stage two) to get a functional multimodal model.

**Comment by yuanlisky** [comment]
> Stage one is focused on aligning the language and vision models, so the alignments are specific to the model (that's why there are different checkpoints for first stage Vicuna 7B and 13B). If you are changing out the LLM, you would have to align the vision model and new LLM (stage one) and finetune the new LLM (stage two) to get a functional multimodal model.

Ok, thank you!
