### ISSUE TITLE
The ability of few-shot in-context learning

### ISSUE THREAD

**Issue by Holly-Max** [Vision-CAIR/MiniGPT-4#307]
Dear authors, MiniGPT-4 is an amazing model. But I'm curious about whether it can do "in-context-learning". I want to do some exploration on it.

**Comment by Sypherd** [comment]
It can do in-context learning out of the box because that does not require changes to any weights/parameters. In-context learning consists of providing the model with input-output examples as part of the prompt. For more effective finetuning that does condition the model itself, you might look at [few-shot finetuning](https://arxiv.org/pdf/2305.16938.pdf).

**Comment by Holly-Max** [comment]
Would you be able to provide some scripts to facilitate implementing this feature?

**Comment by shwetabhardwaj44** [comment]
Hi @yongliang-wu  can you share the code to implement this feature of ICL or provide the sample prompt (with formatting) you passed to MiniGpt4 
Would truly appreciate it.
