### ISSUE TITLE
Interleaved image/text chat

### ISSUE THREAD

**Issue by ogkalu2** [Vision-CAIR/MiniGPT-4#40]
Correct me if i'm wrong but reading the Blip paper, i believe there's no reason why we can't have some kind of interleaved chat with the model correct ? For instance asking a question about one image then asking a question about another image then asking a question that relates the conversation and two images ?

I'm wondering if you could support this in your code if possible ?

**Comment by xiaoqian-shen** [comment]
Hello, thank you for bringing up this concern. Yes, you are right, our model can have interleaved chat with multiple images, and our code is capable of supporting such a task. However, in the Gradio demo, we limited users to only one image per conversation due to considerations of throughout and logical flow. You can try out our code in your own machine, and just set `gr.update(interactive=True)` [demo.py](https://github.com/Vision-CAIR/MiniGPT-4/blob/9390fbd46a44b133af327eb0de5084ae5eb3c623/demo.py#L81).

**Comment by ogkalu2** [comment]
> Hello, thank you for bringing up this concern. Yes, you are right, our model can have interleaved chat with multiple images, and our code is capable of supporting such a task. However, in the Gradio demo, we limited users to only one image per conversation due to considerations of throughout and logical flow. You can try out our code in your own machine, and just set `gr.update(interactive=True)` [demo.py](https://github.com/Vision-CAIR/MiniGPT-4/blob/9390fbd46a44b133af327eb0de5084ae5eb3c623/demo.py#L81). And pass img_list to [upload_img](https://github.com/Vision-CAIR/MiniGPT-4/blob/9390fbd46a44b133af327eb0de5084ae5eb3c623/minigpt4/conversation/conversation.py#L171) instead of reseting the img_list every time you upload a new image.

Oh Ok. Thanks, i'll check the code out.
